### ISSUE TITLE
You're rescanning the full input string (- a character)  26 times

### ISSUE THREAD

**Issue by robopossum** [mattravenhall/AdventOfCode#1]
https://github.com/mattravenhall/AdventOfCode2018/blob/9801c90cf285c0fd526d3fc69f35a1b66dff7124/Day_05/solveB.py#L60

Rather than removing a character from the whole starting string each time, pre scan the string first. The saves having to process the full string, and gets the same result.

**Comment by mattravenhall** [comment]
Fixed in commit https://github.com/mattravenhall/AdventOfCode/commit/38c096d3406950cda8dbbfb43f88cd176ce6ce6f - the speed increase isn't dramatic, but reading the same file 26 times was an odd 'feature'. Thanks for pointing this out!
